# https://github.com/realm/SwiftLint/blob/master/Rules.md
excluded: # paths to ignore during linting. Takes precedence over `included`.
- LocationsListTests
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - identifier_name
  - duplicate_enum_cases
  - no_extension_access_modifier
  - opening_brace
  - large_tuple
line_length:
    warning: 170
    #error: 200 will active it soon
identifier_name:
    min_length: 2
type_name:
    max_length: 50
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - cyclomatic_complexity
  - empty_string
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
cyclomatic_complexity:
  error: 10
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# force_unwrapping: error
file_length:
  warning: 200
# error: 400 will active it soon
